// <auto-generated />
using System;
using CinemaProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cinema_mng_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221183058_AddGenresAndMovieGenres")]
    partial class AddGenresAndMovieGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaProject.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("SeatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatRow")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TicketTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Триллер"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Боевик"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Фэнтези"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Романтика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Комедия"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Научная фантастика"
                        });
                });

            modelBuilder.Entity("CinemaProject.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Halls", null, t =>
                        {
                            t.HasCheckConstraint("CK_Hall_Type", "Type IN ('standard', 'comfort', 'vip')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            Name = "Зал 1 (Стандартный)",
                            Type = "standard"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            Name = "Зал 2 (Комфортный)",
                            Type = "comfort"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Name = "VIP Зал",
                            Type = "vip"
                        });
                });

            modelBuilder.Entity("CinemaProject.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PopularityScore")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.PriceModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Multiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("real(5)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceModifiers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = "{\"start_time\": \"18:00:00\", \"end_time\": \"22:00:00\"}",
                            Multiplier = 1.2f,
                            Type = "time_slot"
                        },
                        new
                        {
                            Id = 2,
                            Condition = "{\"min_score\": 0.8}",
                            Multiplier = 1.3f,
                            Type = "popularity"
                        });
                });

            modelBuilder.Entity("CinemaProject.Models.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Spacing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Rows", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            Number = 1,
                            Seats = 5,
                            Spacing = "extraWide",
                            Type = "sofa",
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 2,
                            HallId = 1,
                            Number = 2,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            HallId = 1,
                            Number = 3,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 4,
                            HallId = 1,
                            Number = 4,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 5,
                            HallId = 1,
                            Number = 5,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 6,
                            HallId = 1,
                            Number = 6,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 7,
                            HallId = 1,
                            Number = 7,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 8,
                            HallId = 1,
                            Number = 8,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 9,
                            HallId = 1,
                            Number = 9,
                            Seats = 8,
                            Spacing = "wide",
                            Type = "loveSeat",
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 10,
                            HallId = 2,
                            Number = 1,
                            Seats = 5,
                            Spacing = "extraWide",
                            Type = "sofa",
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 11,
                            HallId = 2,
                            Number = 2,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 12,
                            HallId = 2,
                            Number = 3,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 13,
                            HallId = 2,
                            Number = 4,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 14,
                            HallId = 2,
                            Number = 5,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 15,
                            HallId = 2,
                            Number = 6,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 16,
                            HallId = 2,
                            Number = 7,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 17,
                            HallId = 2,
                            Number = 8,
                            Seats = 10,
                            Spacing = "normal",
                            Type = "standard",
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 18,
                            HallId = 2,
                            Number = 9,
                            Seats = 8,
                            Spacing = "wide",
                            Type = "loveSeat",
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 19,
                            HallId = 2,
                            Number = 10,
                            Seats = 6,
                            Spacing = "wide",
                            Type = "recliner",
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 20,
                            HallId = 3,
                            Number = 1,
                            Seats = 8,
                            Spacing = "wide",
                            Type = "loveSeat",
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 21,
                            HallId = 3,
                            Number = 2,
                            Seats = 8,
                            Spacing = "wide",
                            Type = "loveSeat",
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 22,
                            HallId = 3,
                            Number = 3,
                            Seats = 8,
                            Spacing = "wide",
                            Type = "recliner",
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 23,
                            HallId = 3,
                            Number = 4,
                            Seats = 8,
                            Spacing = "wide",
                            Type = "recliner",
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 24,
                            HallId = 3,
                            Number = 5,
                            Seats = 6,
                            Spacing = "wide",
                            Type = "sofa",
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 25,
                            HallId = 3,
                            Number = 6,
                            Seats = 6,
                            Spacing = "wide",
                            Type = "sofa",
                            ZoneId = 5
                        });
                });

            modelBuilder.Entity("CinemaProject.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Multiplier = 1.0m,
                            Name = "Стандартный"
                        },
                        new
                        {
                            Id = 2,
                            Multiplier = 0.8m,
                            Name = "Студенческий"
                        },
                        new
                        {
                            Id = 3,
                            Multiplier = 0.7m,
                            Name = "Пенсионный"
                        });
                });

            modelBuilder.Entity("CinemaProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("Zones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 10.00m,
                            HallId = 1,
                            Name = "Стандартное кресло"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 20.00m,
                            HallId = 1,
                            Name = "Диван"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 18.00m,
                            HallId = 1,
                            Name = "LoveSeats"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 20.00m,
                            HallId = 2,
                            Name = "Диван"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 18.00m,
                            HallId = 2,
                            Name = "LoveSeats"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 15.00m,
                            HallId = 2,
                            Name = "Реклайнер"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 10.00m,
                            HallId = 2,
                            Name = "Стандартное кресло"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 25.00m,
                            HallId = 3,
                            Name = "VIP Диван"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 30.00m,
                            HallId = 3,
                            Name = "VIP Реклайнер"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 28.00m,
                            HallId = 3,
                            Name = "VIP LoveSeats"
                        });
                });

            modelBuilder.Entity("CinemaProject.Models.Booking", b =>
                {
                    b.HasOne("CinemaProject.Models.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaProject.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("TicketType");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("CinemaProject.Models.MovieGenre", b =>
                {
                    b.HasOne("CinemaProject.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaProject.Models.Row", b =>
                {
                    b.HasOne("CinemaProject.Models.Hall", "Hall")
                        .WithMany("Rows")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaProject.Models.Schedule", b =>
                {
                    b.HasOne("CinemaProject.Models.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaProject.Models.Zone", b =>
                {
                    b.HasOne("CinemaProject.Models.Hall", "Hall")
                        .WithMany("Zones")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaProject.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CinemaProject.Models.Hall", b =>
                {
                    b.Navigation("Rows");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("CinemaProject.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
